### ISSUE TITLE
Use the notification exception to annotate the file/line where it occured

### ISSUE THREAD

**Issue by runephilosof-abtion** [Drieam/rspec-github#75]
Instead of only annotating the spec file, also annotate where the exception happened.

Maybe make it configurable which annotations you want.

**Comment by StefSchenkelaars** [comment]
Just to clarify, this would only be in case of an exception right? Because if you have a simple test like `expect(true).to equal false`, you don't have a location other than the spec file.

**Comment by StefSchenkelaars** [comment]
@runephilosof-abtion Have a look at #76. Please test this branch and see if this is what you expect. If this is indeed ok, I can work on making it production ready with configuration etc.

**Comment by runephilosof-abtion** [comment]
It should use the same filtering of files that `--format progress` does, so that only application file are reported.

Example:
```
Failures:

  1) ErrorsController GET #internal_server_error renders 422 status page
     Failure/Error: format.html { render status: :internl_server_error }
     
     ArgumentError:
       Unrecognized status code :internl_server_error
     # ./app/controllers/errors_controller.rb:18:in `block (2 levels) in internal_server_error'
     # ./app/controllers/errors_controller.rb:17:in `internal_server_error'
     # ./spec/controllers/errors_controller_spec.rb:28:in `block (3 levels) in <top (required)>'
```

PR #76 gives this output:
```
::error file=/root/.asdf/installs/ruby/3.3.3/lib/ruby/gems/3.3.0/gems/rack-3.1.7/lib/rack/utils.rb,line=591::ErrorsController GET #internal_server_error renders 422 status page%0A%0AFailure/Error: format.html { render status: :internl_server_error }%0A%0AArgumentError:%0A  Unrecognized status code :internl_server_error
```
